//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloor.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int PartnerID { get; set; }
        public int PartnerTypeID { get; set; }
        public string PartnerName { get; set; }
        public string DirectorName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string LegalAddress { get; set; }
        public string INN { get; set; }
        public Nullable<int> Rating { get; set; }

        public int Discount
        {
            get
            {
                if (this.Sales == null || !this.Sales.Any())
                {
                    return 0;
                }

                int totalQuantity = this.Sales.Sum(s => s.Quantity);

                if (totalQuantity > 300000) return 15;
                if (totalQuantity > 50000) return 10;
                if (totalQuantity > 10000) return 5;

                return 0;
            }
        }

        public virtual PartnerType PartnerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
